""" Author: Lex Bosch
    Date: 2021/03/11

    This script generates JSON files from the idstats file and generated bins.
    The JSON file is in format [{contig:[length, #_mapped_reads, sequence]}]
"""

from json import dump
import pandas as pd
from Bio import SeqIO


def read_idxstats(filepath: str):
    """ Reads the file generated by the samtools function idxstats.
        Turns the file into a dictionary with format {Contig_name : [length, #_mapped_reads]}

    :param filepath: string, Path to idxstats file
    :return: Dictionary with format {Contig_name : [length, #_mapped_reads]}
    """
    stats_df = pd.read_csv(filepath, sep="\t", names=["row_name", "length", "mapped_seg", "unmapped_seg"])
    seq_data_dict = {}
    for row, row2 in stats_df.T.iteritems():
        rowname = row2["row_name"].split(" ")[0]
        lenght = row2["length"]
        mapped_seg = row2["mapped_seg"]
        seq_data_dict[rowname] = [lenght, mapped_seg]
    return seq_data_dict


def read_binning_data(filepath: str, amount_bins: int, seq_data_dict: dict):
    """ Reads a series of binned data. turns the files into dictionary with format


    :param filepath: Path and filename of the files to the bins
    :param amount_bins: Amount of binfiles
    :param seq_data_dict: dictionary in format {Contig_name : [length, #_mapped_reads]}
    :return: returns a list in format [{contig:[length, #_mapped_reads, sequence]}]
    """
    full_indexed_list = []
    for i in range(1, amount_bins+1):
        partial_dict = {}
        for record in SeqIO.parse("{}.{}.fa".format(filepath, i), "fasta"):
            partial_dict[record.description] = seq_data_dict[record.description]
            partial_dict[record.description].append(str(record.seq))
        full_indexed_list.append(partial_dict)
    return full_indexed_list


# SET THESE VARIABLES!
idxstats_path = ""  # Set this variable to the patht to the idxstats file created by samtools
bin_folder = ""  # Set this variable to the folder containing the bins
output_path = ""  # Output path


seq_dict = read_idxstats(idxstats_path)
full_list = read_binning_data(bin_folder, 10, seq_dict)

with open(output_path, "w") as json_out:
    dump(full_list, json_out)